# These are supported funding model platforms

github: nikolay
patreon: nikolay
open_collective: nikolay
ko_fi: nikolay
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: nikolay
issuehunt: nikolay
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: nikolay
buy_me_a_coffee: nikolay
thanks_dev: gh/nikolay
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
